### ISSUE TITLE
Test cropper and clipper

### ISSUE THREAD

**Issue by AnonymousFool** [Micky774/Generative-Models#24]
In the data directory, there are two files, "clippedDataGen.py" and "croppedDataGen.py", which should convert numpy arrays representing individual videos to more convenient forms.

They can be tested by calling the files from command line and using the "--loadDirectory" flag to provide a path to the directory containing the numpy arrays to be converted. The two files should produce new subdirectories called "clipped" and "cropped", respectively, containing the new numpy arrays.

**Comment by Micky774** [comment]
Tested. Works after slight modification and has been successfully applied.
